version: "{build}"
build_script:
- cmd: >-
    build.cmd -Platform x64 -Configuration release

    powershell.exe -File scripts\package-windows\package-windows.ps1 -Version 0.0.0.0
test_script:
- cmd: nunit-console bin\tests\EventStore.BufferManagement.Tests.dll bin\tests\EventStore.Core.Tests.dll bin\tests\EventStore.Projections.Core.Tests.dll /framework:net-4.5 /noshadow
artifacts:
- path: packages/*.*
  name: Binaries ZIP
